services:
  postgres:
    image: postgres:16-alpine
    container_name: cleaning_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleaning_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cleaning_app
    restart: always
    ports:
      - '80:80'
      - '3000:3000'
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: cleaning_db
      JWT_SECRET: super_secret_key_cleaning_platform_2026
      JWT_EXPIRES_IN: 1d
    depends_on:
      - postgres

volumes:
  pgdata: